# Generated by Django 5.1.4 on 2025-01-21 05:31

import django.contrib.auth.models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SellerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/%Y/%m/%d/')),
                ('store_address_line_1', models.CharField(blank=True, max_length=255)),
                ('store_address_line_2', models.CharField(blank=True, max_length=255)),
                ('store_city', models.CharField(blank=True, max_length=100)),
                ('store_state', models.CharField(blank=True, max_length=100)),
                ('store_country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('store_zip_code', models.CharField(blank=True, max_length=10)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US')),
                ('tax_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='seller_profiles/%Y/%m/%d/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US')),
                ('is_verified', models.BooleanField(default=False)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='seller.seller')),
            ],
        ),
    ]
