# Generated by Django 5.1.4 on 2025-01-31 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_cart'),
        ('payment', '0005_alter_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='checkout.checkout'),
        ),
    ]
