# Generated by Django 5.1.4 on 2025-01-31 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_customer_alter_cartitem_cart'),
        ('checkout', '0002_checkout_is_completed_alter_checkout_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart'),
        ),
    ]
