# Generated by Django 5.1.4 on 2025-02-04 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_cart'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
