# Generated by Django 5.1.4 on 2025-02-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkout_platform_charge_checkout_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='platform_charge',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_charge',
        ),
    ]
