# Generated by Django 5.1.4 on 2025-01-31 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_product_alter_orderitem_store'),
        ('products', '0001_initial'),
        ('seller', '0002_sellerprofile_is_onboarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='seller.sellerstore'),
            preserve_default=False,
        ),
    ]
