# Generated by Django 5.1.4 on 2025-02-05 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
