# Generated by Django 5.1.4 on 2025-02-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_checkout_cart'),
        ('orders', '0017_order_orders_orde_custome_242823_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='checkout.shippingaddress'),
        ),
    ]
